### ISSUE TITLE
Is it possible to debug scala-repl-pp and mapping to *.sc source code?

### ISSUE THREAD

**Issue by FFengIll** [mpollmeier/scala-repl-pp#148]
Yes, I can debug the program with scala-repl-pp,
but I can not mapping back to the code (*.sc) when trigger breakpoint.

FYI.

**Comment by mpollmeier** [comment]
That'll be hard at the moment, since currently we concatenate the .sc scripts with predef code etc...

Sorry :(

**Comment by FFengIll** [comment]
thank you anyway
